# config\packages\nelmio_api_doc.yaml

nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Une API exposant des telephones mobiles haut de gamme.
            version: 2.0.0


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc




            