# config\packages\nelmio_api_doc.yaml

nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: BileMo
            description: Une API exposant des telephones mobiles haut de gamme.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    in: header
        security:
            - Bearer: []
        
        paths:
            /api/login_check:
                post:
                    tags:
                        - Login
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Creer un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: 
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        $ref: 

                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refresh_token:
                                                type: string
                        '401':
                            description: Identifiants incorects
                        '400':
                            description: Invalid JSON.
                    security: []

    # models: 
    #     names:
    #         - {alias: MainUser, }

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!(/doc|/doc.json|/token/refresh)$)
        






